openapi: 3.0.1
info:
  title: exporter-trigger
  description: Service that responsible for activating the export geopackage process
  version: 1.0.0
servers:
  - url: http://localhost:80
paths:
  /exportGeopackage:
    post:
      tags:
        - Geopackage Exporter
      summary: Trigger export geopackage process
      operationId: exportGeopackage
      requestBody:
        $ref: '#/components/requestBodies/ExportProcessBody'
      responses:
        200:
          description: OK
          content: {}
        400:
          description: Failed in export validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exportGeopackageErrorBody' 
              examples:
                err_bbox:
                  value:
                    name: 'Error'
                    message: 'Error validating bbox, Cause: CAUSE, Bbox= BBOX'
                err_bbox_area_large:
                  value:
                    name: 'ERR_BBOX_AREA_TOO_LARGE'
                    message: 'BBox area exceeds set limit of ${limit} square km'
                err_bbox_area_small:
                  value:
                    name: 'ERR_BBOX_AREA_TOO_SMALL'
                    message: 'BBox area cannot be smaller than 1 square meter'
                err_bbox_resolution:
                  value:
                    name: 'ERR_BBOX_RESOLUTION_VALIDATION_ERROR'
                    message: 'BBox resolution is too small for wanted zoom level, zoom level: ${zoomLevel}'
        409:
          description: Failed saving duplicated export data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exportGeopackageErrorBody' 
              example:
                name: 'ERR_EXPORT_DATA_DUPLICATION'
                message: 'Failed saving export data because of duplication of unique fields, data=DATA, error=ERROR'
        500:
          description: Server Error
          content: {}
      x-codegen-request-body-name: body
  /getmap:
    post:
      tags:
        - Export tiles to GPKG 
      summary: Trigger export geopackage process
      operationId: exportTilesToGpkg
      requestBody:
        $ref: '#/components/requestBodies/ExportGetmapBody'
      responses:
        200:
          description: OK
          content: {}
        400:
          description: BAD REQUEST - failed in export validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exportGeopackageErrorBody' 
              examples:
                err_bbox:
                  value:
                    name: 'Error'
                    message: 'OpenAPI parameters validation failed'
        500:
          description: Internal Server Error due to unavailable services
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exportGeopackageErrorBody' 
              examples:
                err_bbox:
                  value:
                    name: 'Error'
                    message: 'Other service - could not process the request'

  /exportStatus:
    get:
      tags:
        - Geopackage Execution Status
      summary: Get the status of export jobs
      operationId: getGeopackageExecutionStatus
      # TODO: add pagination parameters in future
      # parameters: # TODO: require parameter in future
      # - in: query
      #   name: userId
      #   schema:
      #     type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exportStatus'
        500:
          description: Server Error
          content: {}

components:
  requestBodies:
    ExportProcessBody:
      description: Export geopackage request
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exportProcess'
    
    ExportGetmapBody:
      description: Export to gpkg via GetMap
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exportGetMap'      

  schemas:
    exportGeopackageErrorBody:
      type: object
      properties:
        name:
          type: string
        message:
          type: string

    layerOption:
      required:
        - url
        - exportType
        - sourceLayer
      type: object
      properties:
        url:
          type: string
          format: uri
          description: URL of tile server that needs to be downloaded
        exportType:
          type: string
          enum: [raster, vector]
          description: >
            Export Type:
             * `raster` - Geopackage of raster tiles
             * `vector` - Geopackage of vector features
        sourceLayer:
          type: string
          description: Source layer name from which the exported file
          
      example:
        url: http://test/geoserver/ows?service=wms
        exportType: raster
        sourceLayer: satellite_5m_layer

    exportGetMap:
      requried:
        - dbId
        - bbox
        - targetResolution
        - url
      type: object
      properties:
        dbId:
            type: string
            format: uuid
            description: ID as the primary key from the Raster Catalog
        bbox:
          type: array
          items:
            type: number
          minItems: 4
          maxItems: 4
          description: Bounding box corners (lower left, upper right)=[minx,miny,maxx,maxy] in crs units as array
        targetResolution:
          type: number
          description: The target resolution in which the tiles will be created - DEGREE to PIXEL
        url:
          type: string
          description: The callback URL to notify the process if finished
        CRS:
          type: string
          description: The CRS to be used, defaults to EPSG:4326
          enum: ['EPSG:4326']
        priority:
          type: number
          description: The priority of the record. Maximum priority = most urgent.
          minimum: 0
          maximum: 1000
    
    exportProcess:
      required:
        - bbox
        - fileName
        - directoryName
        - sizeEst
        - maxZoom
      type: object
      properties:
        fileName:
          type: string
          description: the file name to be created on shared folder
          pattern: '^[a-zA-Z0-9_-]+$'
        directoryName:
          type: string
          description: the directory name to be created on shared folder
          pattern: '^[a-zA-Z0-9_-]+$'
        bbox:
          type: array
          items:
            type: number
          minItems: 4
          maxItems: 4
          description: Bounding box corners (lower left, upper right)=[minx,miny,maxx,maxy] in crs units as array
        exportedLayers:
          type: array
          items:
            $ref: '#/components/schemas/layerOption'
        sizeEst:
          type: number
          description: the file estimated size (Mb)
        maxZoom:
          type: number
          description: the maximum zoom level of the wanted geopackage

      example:
        fileName: test_file
        directoryName: test_directory
        bbox:
          [
            34.811938017107494,
            31.95475033759175,
            34.82237261707599,
            31.96426962177354,
          ]
        exportedLayers:
          - url: http://test/geoserver/ows?service=wms
            exportType: raster
        sizeEst: 30
        maxZoom: 18

    exportStatus:
      type: array
      items:
        type: object
        properties:
          taskId:
            type: string
            format: uuid
            description: unique task id
          userId:
            type: string
            description: user unique id
          directoryName:
            type: string
            description: the directory where the file is stored
            pattern: '^[a-zA-Z0-9_-]+$'
          fileName:
            type: string
            description: file name
            pattern: '^[a-zA-Z0-9_-]+$'
          sizeEst:
            type: number
            description: file's estimated size
          realSize:
            type: number
            description: file's real size
          maxZoom:
            type: number
            description: the maximum zoom level of the wanted geopackage
          polygon:
            type: object
            properties:
              type:
                type: string
              coordinates:
                type: array
                items:
                  type: array
                  items:
                    type: array
                    items:
                      type: integer
            description: the exported polygon
          status:
            type: string
            enum: [Pending, In-Progress, Completed, Failed]
            description: export status
          link:
            type: string
            description: file's full location
          creationDate:
            type: string
            description: export's creation date
            format: date-time
          lastUpdateTime:
            type: string
            description: export's update time
            format: date-time
          expirationTime:
            type: string
            description: export's expiration time
            format: date-time
          progress:
            type: number
            description: export's progress %
          sourceLayer:
            type: string
            description: Source layer name from which the exported file

        example:
          taskId: acb2dd1f-c7cc-4600-bf31-fb42ff387ee2
          userId: tester
          directoryName: saas
          fileName: z
          realSize: 0.12
          polygon:
            type: Polygon,
            coordinates:
              [
                [
                  [34.7862839772771, 32.0933739075861],
                  [34.7865314250815, 32.0933739075861],
                  [34.7865314250815, 32.093634611523],
                  [34.7862839772771, 32.093634611523],
                  [34.7862839772771, 32.0933739075861],
                ],
              ]
          status: Completed
          link: /saas/z.GPKG
          creationDate: 2020-11-10T12:09:01.000Z
          lastUpdateTime: 2020-11-10T12:09:22.000Z
          expirationTime: 2020-12-10T12:09:01.000Z
          progress: 100
          sourceLayer: satellite_5m_layer
